# Generated by Django 6.0 on 2025-12-16 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('work_hours', models.CharField(max_length=100, verbose_name='Часы работы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название страны')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='countries/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('train', 'ЖД билет'), ('air', 'Авиабилет')], max_length=20, verbose_name='Тип билета')),
                ('departure_city', models.CharField(max_length=100, verbose_name='Город отправления')),
                ('arrival_city', models.CharField(max_length=100, verbose_name='Город прибытия')),
                ('departure_date', models.DateTimeField(verbose_name='Дата отправления')),
                ('arrival_date', models.DateTimeField(verbose_name='Дата прибытия')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('available_seats', models.IntegerField(default=50, verbose_name='Доступные места')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'ordering': ['departure_date'],
            },
        ),
        migrations.CreateModel(
            name='TicketBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100, verbose_name='Имя пассажира')),
                ('passenger_email', models.EmailField(max_length=254, verbose_name='Email пассажира')),
                ('passenger_phone', models.CharField(max_length=20, verbose_name='Телефон пассажира')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтвержден')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.ticket', verbose_name='Билет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование билета',
                'verbose_name_plural': 'Бронирования билетов',
            },
        ),
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100, verbose_name='Имя пассажира')),
                ('passenger_email', models.EmailField(max_length=254, verbose_name='Email пассажира')),
                ('passenger_phone', models.CharField(max_length=20, verbose_name='Телефон пассажира')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтвержден')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.ticket', verbose_name='Билет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ билета',
                'verbose_name_plural': 'Заказы билетов',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название тура')),
                ('description', models.TextField(verbose_name='Описание')),
                ('duration', models.IntegerField(verbose_name='Длительность (дней)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('tour_type', models.CharField(choices=[('beach', 'Пляжный отдых'), ('excursion', 'Экскурсионный'), ('ski', 'Горнолыжный'), ('cruise', 'Круиз'), ('safari', 'Сафари')], max_length=20, verbose_name='Тип тура')),
                ('image', models.ImageField(upload_to='tours/', verbose_name='Изображение')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='EarlyBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('booking_date', models.DateField(verbose_name='Дата бронирования')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Раннее бронирование',
                'verbose_name_plural': 'Ранние бронирования',
            },
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.TextField(verbose_name='Требования')),
                ('processing_time', models.CharField(max_length=50, verbose_name='Срок оформления')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Виза',
                'verbose_name_plural': 'Визы',
            },
        ),
    ]
